// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zovitfmgwhxfawhfcgri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpvdml0Zm1nd2h4ZmF3aGZjZ3JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzQ3NzksImV4cCI6MjA3MzYxMDc3OX0.pNcSETlQQNp4tGZYHZ9DgXV_PqhkJDag6ew_GoFg4Q0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});